spring:
  application:
    name: Chit-Management-App
  datasource:
    url: jdbc:mysql://localhost:3306/chitmanagementapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: YzM2YjEzZmY0ZGU3ZGFkZjFiODJhY2FhOGJkMWNiNjZiNzJjMGU4OGE0YmU4ZjZlYjA1YjI3MTU
  expirationMs: 86400000

server:
  port: 8080